# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install poetry
      run: |
        pip install poetry
    - name: Install dependencies
      run: |
        poetry install
    - name: Run ruff static analyzer
      run: |
        poetry run ruff check mill_game tests
    - name: Run ruff formatter check
      run: |
        poetry run ruff format mill_game tests --check
    - name: Run MyPy
      run: |
        poetry run mypy -p mill_game
        poetry run mypy -p tests
    - name: Test with pytest
      run: |
        poetry run ruff format mill_game tests
